- project:
    name: plugin1
    jobs:
        - '{name}-verify'
        - '{name}-merge'

- job-template:
    name: '{name}-verify'

    project-type: freestyle

    properties:
        - github:
            url: https://github.com/Tallisado/jenkins-plugin1

    scm:
      - git:
            url: https://github.com/Tallisado/jenkins-plugin1
            refspec: '+refs/pull/*:refs/remotes/origin/pr/*'
            branches:
                - '${{sha1}}'
            skip-tag: true

    triggers:
        - github-pull-request:
            github-hooks: true
            trigger-phrase: 'recheck'
            permit-all: true

    # wrappers:
    #     - ssh-agent-credentials:
    #         users:
    #             - '2733d65e-3472-48cb-b0e5-4b9230e3caf9'
    #
    builders:
        - shell: |
            #!/bin/bash
            whoami && ls -al || true

- job-template:
    name: '{name}-merge'

    project-type: freestyle

    properties:
        - github:
            url: https://github.com/Tallisado/jenkins-plugin1

    scm:
      - git:
            url: https://github.com/Tallisado/jenkins-plugin1
            branches:
                - '*/master'
            skip-tag: true
            # credentials-id: 'b0b6daf1-3f2b-4713-a05c-25e971850778'

    triggers:
        - github

    wrappers:
        - ssh-agent-credentials:
            users:
                - '2733d65e-3472-48cb-b0e5-4b9230e3caf9'

    builders:
        - shell: |
            #!/bin/bash
            ls -al || true
