- project:
    name: garbage
    jobs:
        - 'plugin-a-verify'
        - 'plugin-a-merge'
        - 'plugin-a-build'
        - 'plugin-b-verify'
        - 'plugin-b-merge'
        - 'plugin-c-verify'
        - 'plugin-c-merge'
        #- 'plugin-pom-bump'


- job-template:
    name: 'plugin-a-verify'
    node: gateway
    project-type: freestyle

    properties:
        - github:
            url: https://github.com/Tallisado/jenkins-pluginA

    scm:
      - git:
            url: https://github.com/Tallisado/jenkins-pluginA
            refspec: '+refs/pull/*:refs/remotes/origin/pr/*'
            branches:
                - '${{sha1}}'
            skip-tag: true

    triggers:
        - github-pull-request:
            github-hooks: true
            trigger-phrase: 'recheck'
            permit-all: true

    builders:
        - shell: |
            #!/bin/bash
            echo "PluginA - Running Unit Tests"

- job-template:
    name: 'plugin-a-merge'
    node: gateway
    project-type: freestyle

    properties:
        - github:
            url: https://github.com/Tallisado/jenkins-pluginA

    scm:
      - git:
            url: https://github.com/Tallisado/jenkins-pluginA
            branches:
                - '*/master'
            skip-tag: true
            # credentials-id: 'b0b6daf1-3f2b-4713-a05c-25e971850778'

    triggers:
        - github

    builders:
        - shell: |
            #!/bin/bash
            echo "Pom Bump - PluginA (self)"
            echo "Pom Bump - AppB"

- job-template:
    name: 'plugin-a-build'
    node: gateway
    project-type: freestyle

    properties:
        - github:
            url: https://github.com/Tallisado/jenkins-pluginA

    scm:
      - git:
            url: https://github.com/Tallisado/jenkins-pluginA
            branches:
                - '*/master'
            skip-tag: true
            # credentials-id: 'b0b6daf1-3f2b-4713-a05c-25e971850778'

    triggers:
        - github

    builders:
        - shell: |
            #!/bin/bash
            mvn clean install

# PLUGIN B

- job-template:
    name: 'plugin-b-verify'
    node: gateway
    project-type: freestyle

    properties:
        - github:
            url: https://github.com/Tallisado/jenkins-pluginB

    scm:
      - git:
            url: https://github.com/Tallisado/jenkins-pluginB
            refspec: '+refs/pull/*:refs/remotes/origin/pr/*'
            branches:
                - '${{sha1}}'
            skip-tag: true

    triggers:
        - github-pull-request:
            github-hooks: true
            trigger-phrase: 'recheck'
            permit-all: true

    # wrappers:
    #     - ssh-agent-credentials:
    #         users:
    #             - '2733d65e-3472-48cb-b0e5-4b9230e3caf9'
    #
    builders:
        - shell: |
            #!/bin/bash
            echo "PluginB - Running Unit Tests"

- job-template:
    name: 'plugin-b-merge'
    node: gateway
    project-type: freestyle

    properties:
        - github:
            url: https://github.com/Tallisado/jenkins-pluginB

    scm:
      - git:
            url: https://github.com/Tallisado/jenkins-pluginB
            branches:
                - '*/master'
            skip-tag: true
            # credentials-id: 'b0b6daf1-3f2b-4713-a05c-25e971850778'

    triggers:
        - github

    # wrappers:
    #     - ssh-agent-credentials:
    #         users:
    #             - '2733d65e-3472-48cb-b0e5-4b9230e3caf9'

    builders:
        - shell: |
            #!/bin/bash
            echo "Pom Bump - PluginB (self)"
            echo "Pom Bump - AppA"
            echo "Pom Bump - AppB"


# PLUGIN C
- job-template:
    name: 'plugin-c-verify'
    node: gateway
    project-type: freestyle

    properties:
        - github:
            url: https://github.com/Tallisado/jenkins-pluginC

    scm:
      - git:
            url: https://github.com/Tallisado/jenkins-pluginC
            refspec: '+refs/pull/*:refs/remotes/origin/pr/*'
            branches:
                - '${{sha1}}'
            skip-tag: true

    triggers:
        - github-pull-request:
            github-hooks: true
            trigger-phrase: 'recheck'
            permit-all: true

    # wrappers:
    #     - ssh-agent-credentials:
    #         users:
    #             - '2733d65e-3472-48cb-b0e5-4b9230e3caf9'
    #
    builders:
        - shell: |
            #!/bin/bash
            echo "PluginC - Running Unit Tests"

- job-template:
    name: 'plugin-c-merge'
    node: gateway
    project-type: freestyle

    properties:
        - github:
            url: https://github.com/Tallisado/jenkins-pluginC

    scm:
      - git:
            url: https://github.com/Tallisado/jenkins-pluginC
            branches:
                - '*/master'
            skip-tag: true
            # credentials-id: 'b0b6daf1-3f2b-4713-a05c-25e971850778'

    triggers:
        - github

    # wrappers:
    #     - ssh-agent-credentials:
    #         users:
    #             - '2733d65e-3472-48cb-b0e5-4b9230e3caf9'

    builders:
        - shell: |
            #!/bin/bash
            echo "Pom Bump - PluginC (self)"
            echo "Pom Bump - AppB"
